### ISSUE TITLE
Socrautil is Missing Methods

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-data-utilities#7]
The new socrautil package `__init__` only imports the `Soda` class, but there are a few methods outside of that class that need to be imported.

**Comment by johnclary** [comment]
This is patched as  `v0.0.5` and auto-pushed to `atd-socrata-util-dev` on pypi. Currently testing.

@sergiogcx the pipeline is awesome!

**Comment by sergiogcx** [comment]
Glad the pipeline is working, the libraries in here are based off of individual repos. We may need to put out fires as they show up elsewhere; hopefully soon we can refine our pipeline in our production servers.
